image: node:8

stages:
  - deploy

cache:
  paths:
    - node_modules/
    - functions/node_modules

deploy_production:
  stage: deploy
  environment: Production
  variables:
    REACT_APP_GOOGLE_API_KEY: $REACT_APP_GOOGLE_API_KEY
  only:
    - master
  script:
    - npm i -g firebase-tools
    - npm i
    - npm --prefix ./functions i ./functions
    - npm run build
    - firebase use production --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY